language: node_js
node_js:
  - 12.13.0
before_script:
  - git submodule init
  - git submodule update
  - npm install -g gatsby-cli
deploy:
  provider: script
  script: . ./build.sh
  skip_cleanup: true
  keep_history: true
  on:
    branch: master