language: node_js
node_js:
  - 12.13.0
before_script:
  - npm install -g gatsby
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: 
  on
    branch: master