language: node_js
git: 
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
node_js:
  - 12.13.0
before_script:
  - npm install -g gatsby-cli
deploy:
  provider: script
  script: . ./build.sh
  skip_cleanup: true
  keep_history: true
  on:
    branch: master